# Generated by Django 5.0.6 on 2024-06-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_rename_senha_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='userrname',
        ),
    ]
