# Generated by Django 5.0.6 on 2024-06-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_rename_nome_usuario_userrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='userrname',
            new_name='username',
        ),
    ]
