# Generated by Django 5.0.6 on 2024-06-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_livro_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
