# Generated by Django 5.0.6 on 2024-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_alter_usuario_email_alter_usuario_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
