# Generated by Django 5.0.6 on 2024-06-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0007_delete_livro_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Nome: ')),
                ('author', models.CharField(max_length=255, verbose_name='Autor: ')),
                ('genre', models.CharField(max_length=255, verbose_name='Gênero: ')),
                ('category', models.CharField(max_length=255, verbose_name='Categoria: ')),
                ('image', models.ImageField(upload_to='livro_images/', verbose_name='Imagem')),
            ],
        ),
    ]
