# Generated by Django 5.0.6 on 2024-06-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0008_livro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
