# Generated by Django 5.0.6 on 2024-06-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0010_livro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
