# Generated by Django 5.0.6 on 2024-06-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0014_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='category',
        ),
    ]
