# Generated by Django 5.0.6 on 2024-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0015_remove_livro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='download',
            field=models.FileField(upload_to='pdf/', verbose_name='URL'),
        ),
    ]
